plugins:
  retort_enabled:
    default: true
    client: true
  retort_limited_emoji_set:
    default: false
    client: true
  retort_allowed_emojis:
    default: "relaxed|laughing|+1|heart|rage|poop"
    client: true
  retort_allow_multiple_reactions:
    default: true
  retort_disabled_categories:
    default: ""
    client: true
  retort_max_per_day: 50
  retort_tl2_max_per_day_multiplier: 1.5
  retort_tl3_max_per_day_multiplier: 2
  retort_tl4_max_per_day_multiplier: 3
  retort_alternate_count:
    default: false
    client: true
